class Constants():
    def robot_base_constants(self):
        global DIFFERENTIAL_DRIVE_CURRENT

        global LAUNCH_WHEEL_CURRENT, FEEDER_WHEEL_CURRENT, ROLLER_CLAW_CURRENT
        global LAUNCH_WHEEL_SPEED, FEEDER_WHEEL_SPEED, ROLLER_CLAW_SPEED

        global CLIMBER_CURRENT, CLIMBER_SPEED
        global LEFT_FRONT_SPEED, RIGHT_FRONT_SPEED

        DIFFERENTIAL_DRIVE_CURRENT = 100
        LEFT_FRONT_SPEED, RIGHT_FRONT_SPEED = (0, 0)

        LAUNCH_WHEEL_CURRENT, FEEDER_WHEEL_CURRENT, ROLLER_CLAW_CURRENT = (145, 145, 100)
        LAUNCH_WHEEL_SPEED, FEEDER_WHEEL_SPEED, ROLLER_CLAW_SPEED = (0, 0, 0)

        CLIMBER_CURRENT, CLIMBER_SPEED = (100, 0)


    
    def autonomous_constants(self):
        global AUTONOMOUS_MODE
        AUTONOMOUS_MODE = "null"

        
